### ISSUE TITLE
Broken link to Linux Kernel documentation

### ISSUE THREAD

**Issue by unixsurfer** [elastic/engineering#5]
In https://github.com/elastic/engineering/blob/master/development_constitution.md#designing-features the [link]( https://www.kernel.org/doc/Documentation/development-process/4.Coding) to Linux Kernel documentation returns 404, the correct link is  https://www.kernel.org/doc/html/latest/process/4.Coding.html

**Comment by drewr** [comment]
Fixed in #3 45766753a15116ba307fa1ffa61712d5d5a4625e
